### ISSUE TITLE
Make prepare fails with "Hunk #1 FAILED at 15."

### ISSUE THREAD

**Issue by DTMad** [rancher/partner-charts#179]
**Overview**

During the update process of the Dynatrace-oneagent-operator from the currently existing 0.8.0 version to the new 0.10.2 version I experienced troubles when running `make prepare`

**Steps to reproduce**

1. Forked latest state of partner-charts repo
2. Created a new branch based on the `main-source` branch
3. Updated the `url` field in `/packages/dynatrace-oneagent-operator/package.yaml` from 
`https://raw.githubusercontent.com/Dynatrace/helm-charts/master/repos/stable/dynatrace-oneagent-operator-0.8.0.tgz` 
to 
`https://raw.githubusercontent.com/Dynatrace/helm-charts/master/repos/stable/dynatrace-oneagent-operator-0.10.2.tgz`
4. Set package variable `export PACKAGE=dynatrace-oneagent-operator`
5. Run `make prepare`

**Error**

```sh
INFO[0000] Pulling https://raw.githubusercontent.com/Dynatrace/helm-charts/master/repos/stable/dynatrace-oneagent-operator-0.10.2.tgz from upstream into charts
INFO[0000] Loading dependencies for chart
INFO[0000] Applying changes from generated-changes
INFO[0000] Applying: generated-changes/patch/Chart.yaml.patch
ERRO[0000]
patching file Chart.yaml
Hunk #1 FAILED at 15.
1 out of 1 hunk FAILED -- saving rejects to file Chart.yaml.rej
FATA[0000] Encountered error while preparing main chart: Encountered error while trying to apply changes to charts: Unable to generate patch with error: exit status 1
make: *** [Makefile:8: prepare] Error 1
```

Sadly the error message is not very descriptive

**Comment by PennyScissors** [comment]
Hello @DTMad, this is expected behavior. When you update the url and different chart is pulled and the patch may not apply correctly so .rej and .orig files are created to help solve the conflicts. To fix this you need to apply the changes in the patch files manually. My preferred method is before updating the url and running make prepare I move the patch file that gave me problems out of the generated-changes directory to prevent that error, then apply the changes from the patch manually and run make patch to save them in a new patch file. Make sure the old patch files and any .orig or .rej files are not included in your PR.

**Comment by PennyScissors** [comment]
Closing this as there hasn't been any activity in a while
