### ISSUE TITLE
[Kubecost] error on make prepare command

### ISSUE THREAD

**Issue by itscalvinwang** [rancher/partner-charts#52]
Hi. I'm working on integrating Kubecost into the Rancher partner charts, but I've run into an issue I can't seem to figure out on the `make prepare CHART=kubecost` command. I've been following the README instructions, and have forked a repo [here](https://github.com/kubecost/partner-charts/tree/main-source).

At first, I was running into `Error: Chart.yaml file is missing` when running the make script, which I traced to this [line](https://github.com/kubecost/partner-charts/blob/4e502b5c40f914aceb4cc973a91a24d836ce3a74/scripts/prepare-subcharts#L81) in the script (`helm dependency update` command)

After further debugging on the command, and implementing the change mentioned in [this comment](https://github.com/helm/helm/issues/3585#issuecomment-369919170), I'm still running into a chart not found error when running `helm dependency update`:

```
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "kubecost" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 3 charts
Save error occurred:  directory charts/prometheus not found
Deleting newly downloaded charts, restoring pre-update state
Error: directory charts/prometheus not found
```
I initially suspected that the issue was that the `kube-state-metrics` repo URL in the prometheus subchart's `requirements.yaml` file had changed, as described in this [Helm blog post](https://helm.sh/blog/new-location-stable-incubator-charts/), but updating the URL in the file, or deleting prometheus `requirements.yaml` altogether didn't have any effect.

Has anyone encountered this problem before? I'd greatly appreciate help from someone more knowledgeable on this problem.

**Comment by maggieliu** [comment]
@PennyScissors Can you help and see if you spot any issue with their chart that could cause this issue?

**Comment by PennyScissors** [comment]
@itscalvinwang Thanks for submitting this issue. The problem seems to be the way the dependencies are managed in the parent chart's `requirements.yaml` is not a common case and therefore unsupported by our prepare/patch scripts. I'll need to investigate this further and discuss with the team what's the best fix.

**Comment by itscalvinwang** [comment]
@PennyScissors Thanks for looking into it. After further investigation, I don't think you need to worry too much about supporting it. Apparently the `requirements.yaml` is deprecated and we don't need it to deploy. I seem to have found a workaround detailed [here](https://github.com/kubecost/partner-charts/pull/2), but am still blocked on some things from our end.

Just a heads up for later testing; our product won't successfully install on a local Rancher cluster with the default `values.yaml` because our helm charts create PV claims which assume the use of a [volume plugin](https://kubernetes.io/docs/concepts/storage/storage-classes/#provisioner) with dynamic internal provisioning on the user end. To test everything else locally, you need to set the four `persistentVolume` fields in `values.yaml` to `false`.

**Comment by PennyScissors** [comment]
@itscalvinwang Glad to know you found a work around. As for the PVCs, you can set those values to `false` through the `questions.yaml` and let users enable it through the UI as needed so it would be their responsibility to setup those PVCs before installing the chart.

Here an [example]( https://github.com/rancher/charts/blob/b2bbf61363fac44f53cf3861c08dbc85de3dac8f/charts/cost-analyzer/v1.57.2/questions.yaml#L12) from the cost-analyzer chart I migrated to our old repo a while back. Your `questions.yaml` might end up looking completely different, since I might have added fields that aren't really needed in common use cases, but you get the idea.

**Comment by AjayTripathy** [comment]
@PennyScissors just want to reiterate that although we have a workaround, it's not ideal, and we'd much prefer to use a rancher makefile on the chart as-is. Is it not simple to just use some sort of a rancher makefile without helm dep up for us? We don't actually run helm dep up in our builds, so it sounds like the call to this in the Rancher makefile is the only thing blocking?

**Comment by itscalvinwang** [comment]
Resolved: https://github.com/rancher/partner-charts/pull/53
