### ISSUE TITLE
Portworx deployment out of date

### ISSUE THREAD

**Issue by ebauman** [rancher/partner-charts#697]
Based on reports from a user, the Portworx partner chart is using an older deployment model that places resources in `kube-system`. This is no longer the deployment model for contemporary Portworx installations, amongst other changes.

Maybe somebody from Portworx can give this a few minutes of attention.

**Comment by nflondo** [comment]
Hello @ebauman,
The Portworxs application version available in Rancher Partner Catalog (2.11.4) matches the application version of portworks available upstream.  Also, the README in its helm charts states:

> Limitations
> 
>     The portworx helm chart can only be deployed in the kube-system namespace. Hence use "kube-system" in the "Target namespace" during configuration.

Based on the above, it looks like Portworxs helm chart in Rancher partner catalog is working as designed.
HTH

**Comment by reylejano** [comment]
The Portworx partner chart fails uninstall depending on what version of K8s you're on like v1.23.16 (this was RKE2 provisioned by Rancher 2.7.1) because a pre-delete and post-delete job uses a container image for kubectl from lachlanevenson https://github.com/rancher/partner-charts/blob/main-source/charts/portworx/portworx/templates/hooks/post-delete/px-postdelete-unlabelnode.yaml#L36

See lachlanevenson/k8s-kubectl dockerhub, https://hub.docker.com/r/lachlanevenson/k8s-kubectl , as there is no image with a v1.23.16 tag

The upstream Portworx chart uses a kubectl image from bitnami
https://github.com/portworx/helm/blob/master/charts/portworx/templates/hooks/post-delete/px-postdelete-unlabelnode.yaml#L36

**Comment by nflondo** [comment]
> The Portworx partner chart fails uninstall depending on what version of K8s you're on like v1.23.16 (this was RKE2 provisioned by Rancher 2.7.1) because a pre-delete and post-delete job uses a container image for kubectl from lachlanevenson https://github.com/rancher/partner-charts/blob/main-source/charts/portworx/portworx/templates/hooks/post-delete/px-postdelete-unlabelnode.yaml#L36
> 
> See lachlanevenson/k8s-kubectl dockerhub, https://hub.docker.com/r/lachlanevenson/k8s-kubectl , as there is no image with a v1.23.16 tag
> 
> The upstream Portworx chart uses a kubectl image from bitnami https://github.com/portworx/helm/blob/master/charts/portworx/templates/hooks/post-delete/px-postdelete-unlabelnode.yaml#L36

@reylejano This is a different issue than the original on this PR, would you open a new PR for this issue please?
